### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by lochakho** [littleredhat1997/HTTPServer#4]
我发现再测试demo的时候 启动的时候 时常会报溢出
LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetectionLevel=advanced' or call ResourceLeakDetector.setLevel()

**Comment by zhangbincheng1997** [comment]
这个项目的netty版本很旧了，可能这个版本需要手动回收。
试试：ReferenceCountUtil.release(buff);
